apt install python-pip -y
export LC_ALL=en_US.UTF-8
pip install --upgrade pip

echo "#!/usr/bin/python
# GENERATED BY DEBIAN

import sys

# Run the main entry point, similarly to how setuptools does it, but because
# we didn't install the actual entry point from setup.py, don't use the
# pkg_resources API.
from pip import __main__
if __name__ == '__main__':
    sys.exit(__main__._main())" > /usr/bin/pip

pip install setuptools
pip install shadowsocks

ssserver -p 18400 -k lwjxxxx18400 -m aes-256-cfb -t 600 --workers 2 -d start
